from pathlib import Path
from html import escape
import json
import hashlib

ROOT = Path(__file__).resolve().parent.parent
PHONE = '+447519560119'
SITE = 'https://dayspring-centre-england.vercel.app'
CSS_VERSION = hashlib.sha256((ROOT / 'assets/style.css').read_bytes()).hexdigest()[:12]
JS_VERSION = hashlib.sha256((ROOT / 'assets/app.js').read_bytes()).hexdigest()[:12]
icons = {
'heart':'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
'sprout':'<path d="M12 22V12M12 15C3 15 3 8 3 4c7 0 9 4 9 8M12 12c0-6 4-9 9-9 0 7-3 10-9 10"/>',
'sun':'<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4.2 4.2l2.1 2.1m11.4 11.4 2.1 2.1M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"/>',
'people':'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 4a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5v2"/>',
'shield':'<path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Z"/><path d="m8 12 3 3 5-6"/>',
'pin':'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/>',
'chat':'<path d="M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4Z"/><path d="M8 10h8m-8 4h5"/>'}
def icon(name): return '<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[name]+'</svg>'
def button(text, href, style=''): return f'<a class="button {style}" href="{href}">{text}<span class="arrow" aria-hidden="true">↗</span></a>'
def link(text, href): return f'<a class="text-link" href="{href}">{text}<span aria-hidden="true">↗</span></a>'
def brand(): return '<a class="brand" href="/" aria-label="Dayspring Centre home"><img class="brand-lockup" src="/assets/dayspring-centre-logo.svg" width="230" height="64" alt="Dayspring Centre"></a>'

services = [
('adult-support','Adult care & support','A little support. A fuller life.','Everyday support that respects your choices and helps you live with confidence, connection and independence.','heart'),
('young-adults','Young adult support','Your future. Your next chapter.','Practical skills, new possibilities and the encouragement to take the next step into adult life.','sprout'),
('children-families','Children & families','Room to play. Space to grow.','Nurturing childcare and thoughtful family support, where every child feels safe, included and encouraged.','sun'),
('community-support','Community support','More connection. More belonging.','Support to get out, stay involved and enjoy the people, places and interests that make life yours.','people'),
('consultancy','Care quality & compliance','Better practice. Stronger outcomes.','Practical guidance for care providers, from quality audits and governance to regulatory readiness.','shield')]

def header(active):
    return f'''<a class="skip" href="#main">Skip to main content</a>
<div class="utility"><div class="wrap"><span>Serving: England.</span><div class="utility-links"><a class="safeguarding-utility" href="/safeguarding.html">Safeguarding</a><button type="button" data-accessibility>Accessibility</button><a href="tel:+447519560119">{PHONE}</a></div></div></div>
<header class="site-header"><div class="wrap header-inner">{brand()}<button class="menu-toggle" aria-controls="primary-nav" aria-expanded="false" type="button">Menu ☰</button><nav id="primary-nav" class="desktop-nav" aria-label="Main navigation"><a href="/about.html" {'aria-current="page"' if active=='about' else ''}>About us</a><details class="nav-menu"><summary>Our services</summary><div class="nav-dropdown">{''.join(f'<a href="/{s[0]}.html">{s[1]}</a>' for s in services)}<a href="/services.html">All services</a></div></details><a href="/children-families.html">Children & families</a><a class="secondary-nav" href="/consultancy.html">Consultancy</a><a class="secondary-nav" href="/careers.html">Careers</a><a href="/contact.html">Contact</a><a class="mobile-referral" href="/referrals.html" hidden>Make a referral</a></nav>{button('Make a referral','/referrals.html','header-cta')}</div></header>'''

def footer():
    return f'''<section class="cta"><div class="wrap cta-inner"><div><span class="eyebrow">Let's take the next step, together</span><h2>Good support starts<br>with a conversation.</h2><p>You don’t need to have all the answers. Tell us what matters to you, and we’ll help you explore the possibilities.</p></div><div class="cta-actions">{button('Let’s talk','/contact.html')}<a href="tel:+447519560119">Or call {PHONE}</a></div></div></section>
<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div class="footer-intro">{brand()}<p>Care. Children. Community. Compliance.<br>Trusted support. Stronger outcomes.</p><p>Serving: England.</p></div><div class="footer-column"><h3>Support for you</h3>{''.join(f'<a href="/{s[0]}.html">{s[1]}</a>' for s in services)}<a href="/referrals.html">Professionals & referrals</a></div><div class="footer-column"><h3>Get to know us</h3><a href="/about.html">Our story & values</a><a href="/assets/dayspring-centre-logo.zip" download>Download our logo</a><a href="/areas.html">Areas we cover</a><a href="/careers.html">Work with us</a><a href="/safeguarding.html">Safeguarding</a><a href="/complaints.html">Feedback & complaints</a><a href="/contact.html">Get in touch</a></div><div class="footer-column"><h3>Here to help</h3><a href="tel:+447519560119">{PHONE}</a><p class="registration-details">ICO Data Protection Registration<br>No. 00014845068</p><p>Registered office:<br>2 Athena Apartment<br>Jubilee Way, Sidcup<br>DA14 4BL, England</p><a href="https://reports.ofsted.gov.uk/search?q=EY552018" target="_blank" rel="noopener">Ofsted Registered Childcare Provider<br>EY552018 ↗</a></div></div><div class="footer-bottom"><div>© {2026} Dayspring Centre Limited · Company no. <a href="https://find-and-update.company-information.service.gov.uk/company/11290144">11290144</a></div><div><a href="/privacy.html">Privacy</a> · <a href="/cookies.html">Cookies</a> · <a href="/accessibility.html">Accessibility</a> · <a href="/terms.html">Terms</a> · <a href="/equality.html">Equality</a> · <a href="/modern-slavery.html">Modern slavery</a> · <button data-cookie-settings type="button">Cookie settings</button></div></div><p class="image-disclosure">Website imagery is illustrative and does not depict Dayspring Centre staff or people receiving our services.</p></div></footer>
<div class="mobile-call"><a href="tel:+447519560119">Call {PHONE}</a><a href="/referrals.html">Make a referral ↗</a></div>
<aside class="cookie-banner" hidden aria-label="Cookie information"><h2>A little note about your privacy</h2><p>We use no advertising or analytics cookies. We only save your display preferences and this notice choice on your device.</p><button class="button" data-cookie-dismiss type="button">That’s fine</button><a href="/cookies.html">Read our cookie notice</a></aside>
<dialog class="access-dialog" aria-labelledby="access-title"><button type="button" class="close-dialog" aria-label="Close accessibility settings">×</button><h2 id="access-title">Make yourself comfortable</h2><p>Choose the display that works best for you.</p><div class="access-row"><button data-text-size aria-pressed="false" type="button">Larger text</button><button data-contrast aria-pressed="false" type="button">Higher contrast</button></div><p>You can also zoom using your browser. We respect your device’s reduced motion preference.</p><a href="/accessibility.html">Accessibility information</a></dialog>'''

pages = {}
def page(slug,title,description,content):
    canonical = SITE + ('/' if slug=='index' else f'/{slug}.html')
    schema = {'@context':'https://schema.org','@type':'Organization','name':'Dayspring Centre Limited','url':SITE,'telephone':'+447519560119','areaServed':'England','address':{'@type':'PostalAddress','streetAddress':'2 Athena Apartment, Jubilee Way','addressLocality':'Sidcup','postalCode':'DA14 4BL','addressCountry':'GB'}}
    html=f'''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Dayspring Centre</title><meta name="description" content="{escape(description,quote=True)}"><meta name="theme-color" content="#164e4a"><link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="en_GB"><meta property="og:title" content="{escape(title,quote=True)} | Dayspring Centre"><meta property="og:description" content="{escape(description,quote=True)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{SITE}/assets/children-play-hero.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/dayspring-centre-icon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="/assets/style.css?v={CSS_VERSION}"><script type="application/ld+json">{json.dumps(schema)}</script><script src="/assets/app.js?v={JS_VERSION}" defer></script></head><body>{header(slug)}<main id="main">{content}</main>{footer()}</body></html>'''
    html=html.replace('<h3>Here to help</h3>', '<h3>Here to help</h3><a class="email-link" href="mailto:dayspringcentre@dayspringcentre.co.uk">dayspringcentre@<wbr>dayspringcentre.co.uk</a>')
    html=html.replace('This planner creates a summary on your device. It does not send an enquiry. Call us to start a conversation and arrange how to share further information safely.', 'Prepare a general enquiry, then open it in your email app to review and send to dayspringcentre@dayspringcentre.co.uk. This website does not send it automatically. For detailed referrals or CVs, contact us to agree a suitable route.')
    html=html.replace('I understand this summary stays on my device and is not submitted to Dayspring Centre.', 'I understand I need to review and send the enquiry from my email app; this website does not submit it automatically.')
    html=html.replace('Create my conversation summary', 'Prepare my enquiry')
    html=html.replace('They do not submit an enquiry to Dayspring Centre or store form contents in browser storage.', 'They do not submit an enquiry to Dayspring Centre or store form contents in browser storage. If you choose “Open email draft”, the summary is passed to your email application so you can review and send it. Sending it shares the details with Dayspring Centre at dayspringcentre@dayspringcentre.co.uk.')
    html=html.replace('<h2>We’re ready to listen.</h2>', '<h2>We’re ready to listen.</h2><p>Email <a class="email-link" href="mailto:dayspringcentre@dayspringcentre.co.uk">dayspringcentre@dayspringcentre.co.uk</a> or call us to discuss your enquiry.</p>')
    (ROOT/f'{slug}.html').write_text(html,encoding='utf-8')
    pages[slug] = title

def pagehero(eyebrow,title,lead,action='Talk to us',href='/contact.html'):
    secondary = button('Explore services','/services.html','outline') if href.startswith('tel:') else button('Call '+PHONE,'tel:+447519560119','outline')
    return f'<div class="wrap breadcrumb"><a href="/">Home</a> <span aria-hidden="true">/</span> {eyebrow}</div><section class="page-hero"><div class="wrap"><span class="eyebrow">{eyebrow}</span><h1>{title}</h1><p class="lead">{lead}</p>'+ (f'<div class="hero-actions">{button(action,href)}{secondary}</div>' if action else '')+'</div></section>'
def layout(content,sidebar=True):
    side=f'<aside class="sidebar"><span class="eyebrow">A good place to start</span><h3>Let’s find the right support.</h3><p>Tell us a little about your situation. We’ll listen, answer your questions and explain the next steps.</p>{button("Get in touch","/contact.html")}<a class="phone" href="tel:+447519560119">{PHONE}</a><small>Supporting England. Availability is confirmed after an initial discussion.</small></aside>' if sidebar else ''
    return f'<section class="section"><div class="wrap page-layout"><div class="prose">{content}</div>{side}</div></section>'
def ul(items): return '<ul class="support-list">'+''.join(f'<li>{s}</li>' for s in items)+'</ul>'
def smallcards(items): return '<div class="cards-small">'+''.join(f'<div class="small-card"><h3>{t}</h3><p>{p}</p></div>' for t,p in items)+'</div>'
def servicecards(items):
    return ''.join(f'<article class="service-card"><span class="card-number">0{services.index(s)+1}</span><div class="service-icon">{icon(s[4])}</div><h3>{s[1]}</h3><p>{s[3]}</p>{link("Explore "+("consultancy" if s[0]=="consultancy" else "support"),"/"+s[0]+".html")}</article>' for s in items)

faq=[('What support is right for me or my family?','Start with a conversation. We will listen to what is working well, where you would like help and what you hope to achieve. Together, we can explore whether our services are the right fit.'),('Which areas do you cover?','We are based in Sidcup and support communities across England. Availability, travel and the type of support needed are discussed before any service is agreed.'),('Can I make a referral for someone else?','Families and professionals can contact us to discuss a referral. Please make sure you have an appropriate basis for sharing someone’s information. Start with a general enquiry; we will explain how to share detailed information safely.'),('Is your childcare registered with Ofsted?','Our childcare provision is registered with Ofsted under registration number EY552018, as set out in our service information. This relates to childcare provision and should not be read as a registration or rating for our other services.'),('How much does support cost?','Costs depend on the support needed, its frequency and location. We discuss the options and provide an individual quotation before you decide. Please call us to talk through your needs and any funding arrangements.')]
faqhtml=''.join(f'<details class="faq-item"><summary>{q}</summary><p>{a}</p></details>' for q,a in faq)
steps=[('Let’s talk','An enquiry or referral opens the conversation.'),('We listen','We learn what matters most to you.'),('We understand','We assess needs, strengths and suitability.'),('We plan','Together, we agree your support and goals.'),('We support','The right arrangements are put in place.'),('We review','We keep listening as your needs change.')]

home=f'''<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><span class="eyebrow">Care · Children · Community · Compliance</span><h1>Trusted support.<br><em>Stronger</em><br>outcomes.</h1><p>For the small steps and the big milestones.<br>Compassionate support for children, adults and families, shaped around what matters to you.</p><div class="hero-actions">{button('Find your support','/services.html')}{button('Get to know us','/about.html','outline')}</div><div class="hero-reassurance"><span><b class="check">✓</b> People first. Always.</span><span><b class="check">✓</b> Supporting our communities</span></div></div><div class="hero-art"><svg class="sun-decoration" viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="50" cy="50" r="25"/><path d="M50 1v14m0 70v14M1 50h14m70 0h14M15 15l10 10m50 50 10 10M15 85l10-10m50-50L85 15M31 4l5 13m28 66 5 13M4 31l13 5m66 28 13 5M4 69l13-5m66-28 13-5M31 96l5-13m28-66 5-13"/></svg><div class="hero-photo-frame"><img class="hero-photo" src="/assets/children-play-hero.jpg" width="1400" height="933" alt="A caring childcare practitioner supporting children as they play together with wooden toys" fetchpriority="high"></div><button class="motion-toggle" type="button" data-motion-toggle aria-pressed="false" hidden>Pause image motion</button><span class="hero-aside">ROOTED IN KINDNESS</span><div class="photo-caption"><span class="heart" aria-hidden="true">♡</span><div><strong>Every person. Every possibility.</strong><small>Support that sees the whole you.</small></div></div></div></div></section>
<div class="trust-band"><div class="wrap trust-grid"><div class="trust-item">{icon('shield')}<span>Ofsted-registered childcare<small>Registration no. EY552018</small></span></div><div class="trust-item">{icon('heart')}<span>Person-centred support<small>Your choices. Your goals.</small></span></div><div class="trust-item">{icon('people')}<span>Every stage of life<small>Children, adults & families</small></span></div><div class="trust-item">{icon('pin')}<span>Serving: England<small>Support across the country</small></span></div></div></div>
<section class="section section-white" id="services"><div class="wrap"><div class="section-heading"><div><span class="eyebrow">Different needs. The same care.</span><h2>The right support,<br>at the right moment.</h2></div><p>Life doesn’t come with a single path.<br>Our services meet you where you are, and help you move forward.</p></div><div class="service-grid">{servicecards(services[:3])}</div><div class="service-grid secondary">{servicecards(services[3:])}</div><div class="who-row">A place for everyone who needs us.<div class="who-tags"><span>Children</span><span>Young people</span><span>Adults</span><span>Families</span><span>Professionals & commissioners</span><span>Care providers</span></div></div></div></section>
<section class="section"><div class="wrap about-grid"><div class="about-visual"><img src="/assets/community.jpg" width="800" height="800" loading="lazy" alt="Family members spending a relaxed moment together outdoors"><div class="about-note">Big on kindness.<br>Built around you.</div></div><div class="about-copy"><span class="eyebrow">The Dayspring Centre difference</span><h2>We see a person.<br>Not just a care plan.</h2><p>A favourite walk. A new skill. The confidence to try something for the first time. These are the everyday moments that meaningful support makes possible.</p><p>We take time to understand your world—your strengths, your wishes and the people who matter to you. Then we work together to shape support that feels right.</p><div class="value-list"><div><span class="check">✓</span>Safety at the heart</div><div><span class="check">✓</span>Dignity & choice</div><div><span class="check">✓</span>Kindness in the everyday</div><div><span class="check">✓</span>A place to belong</div></div>{link('Our story & values','/about.html')}</div></div></section>
<section class="section journey"><div class="wrap"><div class="section-heading"><div><span class="eyebrow">A clear path forward</span><h2>One conversation.<br>A world of possibility.</h2></div><p>Finding support can feel like a big step.<br>We’ll make the next steps clear, and take them with you.</p></div><div class="steps">{''.join(f'<div class="step"><div class="step-num">0{i+1}</div><h3>{t}</h3><p>{p}</p></div>' for i,(t,p) in enumerate(steps))}</div><div class="journey-bottom"><span>At every stage, your voice is part of the plan.</span><a href="/contact.html">Start a conversation <span aria-hidden="true">↗</span></a></div></div></section>
<section class="section section-white"><div class="wrap"><div class="professional-banner"><div><span class="eyebrow">For professionals & care providers</span><h2>Better outcomes begin<br>with good partnerships.</h2><p>Whether you’re coordinating someone’s support or strengthening your care service, we bring a thoughtful, practical approach to working together.</p></div>{button('Make a professional referral','/referrals.html')}</div><div class="areas-strip"><p><strong>Serving: England.</strong><br>Support across England, with availability discussed around your needs.</p>{link('Explore our coverage','/areas.html')}</div></div></section>
<section class="section"><div class="wrap faq-layout"><div class="faq-intro"><span class="eyebrow">A little clarity</span><h2>Questions?<br>You’re in good company.</h2><p>Here are a few things people often ask. If yours isn’t here, we’d be happy to help.</p>{link('Ask us a question','/contact.html')}</div><div>{faqhtml}</div></div></section>'''
page('index','Trusted support. Stronger outcomes.','Compassionate childcare, adult and community support, young adult services and care quality consultancy. Based in Sidcup, supporting England.',home)
page('services','Our services','Explore care, childcare, community support and quality consultancy from Dayspring Centre in England.',pagehero('Our services','Support for life,<br>in all its possibilities.','From a child’s first discoveries to a more independent everyday life, our services begin with the person.','Find your next step','#service-options')+f'<section class="section section-white" id="service-options"><div class="wrap"><div class="service-grid">{servicecards(services[:3])}</div><div class="service-grid secondary">{servicecards(services[3:])}</div></div></section>')

about='''<h2>A place to feel heard.</h2><p>Dayspring Centre Limited is a care, childcare, community support and professional consultancy organisation based in Sidcup. We welcome enquiries from individuals, families and organisations in England.</p><p>We believe good support begins by listening. It means noticing someone’s strengths, respecting their choices and understanding the life they want to live. Sometimes that means practical help with everyday routines. Sometimes it means encouragement, connection or simply time to be heard.</p><h2>Our mission</h2><p>To provide safe, compassionate support that helps children, young people and adults build independence, wellbeing and quality of life, while helping care organisations strengthen the quality of their services.</p><h2>Our vision</h2><p>To be a trusted part of the communities we serve, helping people and organisations make positive changes that last.</p><h2>The values behind our work</h2>'''+smallcards([('Safety','People’s welfare and safeguarding guide our decisions.'),('Compassion','Kindness, patience and understanding belong in every interaction.'),('Dignity & choice','Your rights, privacy and decisions matter.'),('Inclusion','Culture, identity, beliefs, abilities and differences are respected.'),('Accountability','We take responsibility for our actions and communicate clearly.'),('Continuous improvement','We listen to feedback, reflect and look for ways to do better.')])+'''<h2>The people behind your support</h2><p>Trust grows when you know who you’re working with. Before support begins, we will explain the proposed arrangements, the roles involved and who to contact with questions. Ask us about the experience and suitability of the people who would support you.</p><h2>Registration & professional standards</h2><p>ICO Data Protection Registration No. <strong>00014845068</strong>. Dayspring Centre Limited is registered with the Information Commissioner’s Office under this registration number.</p><p>Our childcare provision is Ofsted registered under registration number <a href="https://reports.ofsted.gov.uk/search?q=EY552018">EY552018</a>. This registration relates to childcare; it is not presented as a registration or inspection rating for adult services or consultancy.</p><p>Dayspring Centre Limited is registered in England and Wales, company number <a href="https://find-and-update.company-information.service.gov.uk/company/11290144">11290144</a>.</p><div class="notice">Services are agreed only where we can safely and appropriately meet the person’s needs, within the scope of any applicable registration and legal requirements.</div>'''
page('about','About us','Meet the purpose and values behind Dayspring Centre: safety, compassion, dignity, inclusion and thoughtful support.',pagehero('About Dayspring Centre','People at the heart.<br>Purpose in everything.','We want everyone we support to feel safe, heard and able to take the next step in their own way.')+layout(about))

adult='''<h2>Your everyday life, your way.</h2><p>Having support should help you keep doing the things that make you feel like yourself. We work with you to maintain existing abilities, build confidence and make room for what you enjoy.</p><p>We start by asking what matters to you, what you already do independently and where a little help would make a difference.</p><h2>Support may include</h2>'''+ul(['Companionship and emotional wellbeing','Everyday routines and organisation','Meal planning and preparation','Shopping and household activities','Attending appointments','Community access and social activities','Maintaining relationships and interests','Independent living skills','Correspondence and everyday paperwork','Wellbeing checks','Respite and family support','Reducing loneliness and isolation'])+'''<h2>A plan shaped with you</h2><p>We discuss your preferences, strengths, communication needs and desired outcomes. Family members or relevant professionals can be involved where appropriate and with regard to your wishes.</p><p>Your support plan is reviewed as circumstances change. We want support to remain useful, respectful and responsive.</p><div class="notice"><strong>Finding the right fit</strong><p>We confirm availability and suitability before agreeing support. Activities requiring specific regulatory registration are only provided where they fall within Dayspring Centre’s applicable registration and legal scope. Please contact us to discuss any personal care or specialist needs.</p></div>'''
page('adult-support','Adult care & support','Person-centred everyday support, companionship and independent living support for adults. Speak to Dayspring Centre about your needs.',pagehero('Adult care & support','More choice.<br>More everyday possibility.','Thoughtful support to help you live with dignity, independence and connection.','Enquire about adult support','/contact.html?service=adult')+layout(adult))

young='''<h2>Start with your strengths.</h2><p>Becoming an adult can be exciting, uncertain and everything in between. You might want more confidence getting around, help preparing for work, or a little structure as you take on new responsibilities.</p><p>We focus on your abilities and aspirations. You help set the goals, and we work with you at a pace that makes sense.</p><h2>Skills for your next chapter</h2>'''+ul(['Cooking and meal preparation','Budgeting and money awareness','Personal organisation and routines','Education and training','Preparing for employment','CV and interview preparation','Travel confidence','Community participation','Social skills and relationships','Health and wellbeing','Setting personal goals','Building confidence and self-esteem'])+'''<h2>Making transitions feel more manageable</h2><p>Where appropriate, we work alongside families, education settings and relevant professionals to help make the transition into adulthood more structured. We listen to the young person and keep their preferences central to planning.</p><p>Progress can be a big achievement or a small everyday step. Both deserve to be recognised.</p>'''
page('young-adults','Young adult support','Practical support for young adults with independent living, confidence, education, work preparation and community participation.',pagehero('Young adult support','Your life.<br>Your next chapter.','Build practical skills, discover what you can do and move towards the future you want.','Talk about young adult support','/contact.html?service=young')+layout(young))

children='''<div class="notice"><strong>Ofsted-registered childcare provision</strong><p>Registration number <a href="https://reports.ofsted.gov.uk/search?q=EY552018">EY552018</a>. Please contact us to discuss the age range, sessions and arrangements suitable for your child.</p></div><h2>Small discoveries. Growing confidence.</h2><p>Children need space to be curious, to play and to feel that they belong. We aim to create a nurturing environment where each child is recognised as an individual, and parents and carers feel heard too.</p><p>We take time to understand a child’s interests, routines, communication and support needs. That understanding helps us plan activities and care that are appropriate for them.</p><h2>Explore what may be available</h2>'''+ul(['Childcare','Before-school support','After-school support','School collection','Holiday childcare and activities','Play-based learning','Educational and developmental activities','Community activities','Support with routines','Family support'])+'''<p>Sessions, collection arrangements, age suitability and any additional support are discussed individually and are subject to availability and assessment.</p><h2>Safe, heard and included</h2>'''+smallcards([('Safe','Safeguarding, welfare and appropriate supervision are central to our approach.'),('Heard','We encourage children to express their wishes, feelings and ideas.'),('Included','We respect each child’s background, culture, identity and abilities.'),('Encouraged','We make room for interests, strengths, creativity and new discoveries.')])+'''<h2>Safeguarding comes first</h2><p>People working with children are subject to appropriate safer recruitment procedures for their roles. These may include enhanced DBS checks where required, references, identity and right-to-work checks, employment history and qualification checks, safeguarding training and ongoing supervision.</p><p><a href="/safeguarding.html">Read about safeguarding and how to raise a concern.</a></p>'''
page('children-families','Children & family services','Nurturing childcare and family support from Dayspring Centre. Ofsted childcare registration EY552018. Enquire about sessions and availability.',pagehero('Children & families','A place to belong.<br>A chance to blossom.','Nurturing childcare and family support that makes room for every child’s personality, curiosity and potential.','Make a children’s enquiry','/contact.html?service=children')+layout(children))

community='''<h2>A life connected to your community.</h2><p>The places we go and the people we see are part of what makes life meaningful. If getting out or keeping in touch has become more difficult, a little support can open up possibilities.</p><p>We begin with your interests. That might mean visiting a library, getting back to a local group, attending an appointment or building confidence on a familiar journey.</p><h2>Support may include</h2>'''+ul(['Attending appointments','Shopping and local errands','Community groups and activities','Developing everyday skills','Maintaining hobbies and interests','Building travel confidence','Accessing local services','Reducing social isolation'])+'''<h2>At your pace</h2><p>We discuss your preferences and any practical considerations before making arrangements. Support should help you take part in the community in a way that feels comfortable, meaningful and safe.</p>'''
page('community-support','Community support','Support to attend activities, appointments and local services, maintain relationships and feel more connected to your community.',pagehero('Community support','More connection.<br>A greater sense of belonging.','Practical encouragement to stay involved with the people, places and activities you enjoy.','Explore community support','/contact.html?service=community')+layout(community))

consultancy='''<h2>Quality that lives in everyday practice.</h2><p>Good governance should make it easier to deliver safe, consistent care. Our consultancy helps health and social care providers understand where improvements are needed and turn findings into practical action.</p><p>We work with providers and registered managers to review systems, clarify priorities and develop evidence of improvement. The scope is agreed around your service and its needs.</p><h2>Where we can help</h2>'''+smallcards([('Readiness & mock inspections','Independent reviews against applicable quality and regulatory expectations, including CQC readiness.'),('Quality audits','Reviews of care plans, risk assessments, MAR records, daily records, staff files and quality documentation.'),('Governance reviews','Systems for managing risk, incidents, complaints, safeguarding and continuous improvement.'),('Policies & procedures','Practical reviews and development of policies appropriate to your organisation.'),('Care documentation','Improvements to assessments, support plans, risk assessments and associated records.'),('Medication governance','MAR audits, documentation reviews, PRN governance and competency frameworks.'),('Workforce compliance','Recruitment records, supervision, appraisal, competency and training monitoring.'),('Action & improvement plans','Clear, prioritised SMART actions following audits, inspections or identified concerns.')])+'''<h2>Understand. Improve. Sustain.</h2><p>Our approach moves through assessment, identifying gaps, prioritising action, making improvements, gathering evidence and monitoring progress. We explain why a finding matters and what a useful next step could look like.</p><div class="notice">Dayspring Centre provides independent consultancy. We do not represent CQC or Ofsted, and consultancy cannot guarantee a registration decision, inspection result or rating.</div>'''
page('consultancy','Care quality & compliance consultancy','Practical audits, governance reviews, documentation support and regulatory readiness for health and social care providers in England.',pagehero('Care quality & compliance consultancy','Stronger services.<br>More confident teams.','Practical, independent support to strengthen governance, improve quality and prepare for regulatory scrutiny.','Discuss a consultation','/contact.html?service=consultancy')+layout(consultancy))

def form(kind='general'):
    options=[('general','General enquiry'),('adult','Adult support'),('young','Young adult support'),('children','Children’s services / childcare'),('community','Community support'),('referral','Professional referral'),('consultancy','Compliance consultancy'),('careers','Careers'),('safeguarding','Safeguarding'),('complaints','Complaints')]
    return f'''<form class="form-card enquiry-form" data-default-service="{kind}"><h3>Prepare for our conversation</h3><p class="form-help">This planner creates a summary on your device. It does not send an enquiry. Call us to start a conversation and arrange how to share further information safely.</p><div class="form-grid"><div class="field full"><label for="service">How can we help?</label><select id="service" name="service" required>{''.join(f'<option value="{v}" '+('selected' if v==kind else '')+f'>{t}</option>' for v,t in options)}</select></div><div class="field"><label for="name">Your name *</label><input id="name" name="name" autocomplete="name" maxlength="100" required></div><div class="field"><label for="organisation">Organisation (optional)</label><input id="organisation" name="organisation" autocomplete="organization" maxlength="140"></div><div class="field"><label for="phone">Telephone (optional)</label><input id="phone" name="phone" type="tel" autocomplete="tel" maxlength="30"></div><div class="field"><label for="email">Email (optional)</label><input id="email" name="email" type="email" autocomplete="email" maxlength="180"></div><div class="field"><label for="area">Town or postcode area *</label><input id="area" name="area" maxlength="100" required placeholder="e.g. Sidcup or DA14"></div><div class="field"><label for="preferred">Preferred contact method</label><select id="preferred" name="preferred"><option>Telephone</option><option>Email</option></select></div><div class="field full"><label for="message">What would you like to discuss? *</label><textarea id="message" name="message" maxlength="1500" required aria-describedby="message-help"></textarea><small id="message-help">Please keep this general. Do not enter someone else’s name, medical information, safeguarding details, or other sensitive information.</small></div></div><label class="consent"><input type="checkbox" name="acknowledge" required><span>I understand this summary stays on my device and is not submitted to Dayspring Centre. I have read the <a href="/privacy.html">privacy information</a>.</span></label><button class="button" type="submit">Create my conversation summary <span aria-hidden="true">↗</span></button><noscript><p>This optional planner needs JavaScript. You can contact us directly on <a href="tel:+447519560119">{PHONE}</a>.</p></noscript><div class="form-result" role="status" aria-live="polite" hidden></div></form>'''

referrals='''<h2>Working together, with the person at the centre.</h2><p>We welcome appropriate enquiries from local authorities, social workers, NHS professionals, schools, colleges, housing and community organisations, families and private individuals.</p><p>Our first conversation is about suitability: the person’s needs and wishes, the outcomes sought and whether Dayspring Centre can provide safe, appropriate support.</p><h2>How a referral progresses</h2>'''+smallcards([('01 · Initial enquiry','Contact us with a general outline of the support required.'),('02 · Initial review','We consider suitability, service availability and the next step.'),('03 · Assessment','Where appropriate, we arrange an assessment with the person and relevant representatives.'),('04 · Support planning','We agree outcomes, preferences, identified risks and support arrangements.'),('05 · Getting started','Support begins once the arrangements and any necessary agreements are confirmed.'),('06 · Ongoing review','We review how support is working and respond to changing needs.')])+'''<h2>Sharing information safely</h2><p>Please call before sending personal records. We will agree an appropriate route for sharing detailed referral information, including consent or other relevant authority, communication needs, current support, risks, desired outcomes, proposed start date and funding arrangements.</p><div class="notice"><strong>Start with a general conversation.</strong><p>Do not use the optional planner below to record a referred person’s name, date of birth, full address, health records or detailed risks. It is a preparation tool, not a secure referral submission.</p></div>'''+form('referral')
page('referrals','Professionals & referrals','Discuss a professional or family referral with Dayspring Centre. Clear assessment, support planning and review in England.',pagehero('Professionals & referrals','The right partnership.<br>Better possibilities.','A clear, collaborative referral journey for professionals, families and the people they support.','Start a referral by phone','tel:+447519560119')+layout(referrals))

careers='''<h2>Bring your kindness. Make it count.</h2><p>Good support grows from everyday actions: listening carefully, keeping your word and noticing when someone needs encouragement. We welcome interest from people who share our commitment to dignity, inclusion and dependable support.</p><h2>Areas of work</h2>'''+ul(['Support workers','Care and community support workers','Children’s support workers','Childcare practitioners','Senior support staff','Coordinators','Quality and compliance professionals'])+'''<div class="notice"><strong>Expressions of interest welcome</strong><p>These are areas of work, not a list of confirmed vacancies. Contact us to ask about current opportunities, role requirements and how to apply.</p></div><h2>What matters to us</h2><p>We value people who communicate well, respect professional boundaries, take safeguarding seriously and treat others with dignity. Reliability, accountability and a willingness to learn are just as important as practical skills.</p><h2>Safer recruitment</h2><p>Appointments are subject to appropriate checks for the role. These may include DBS checks where required, references, identity and right-to-work verification, employment history checks and verification of qualifications and experience.</p><h2>Interested in joining us?</h2><p>Call to discuss opportunities and arrange an appropriate way to submit your CV. Please do not include identity documents, background-check certificates or sensitive employment details in an initial enquiry.</p>'''+form('careers')
page('careers','Careers & opportunities','Register your interest in support, childcare, coordination and quality consultancy roles with Dayspring Centre.',pagehero('Careers','A little of your time.<br>A real difference to someone.','Join a conversation about work with purpose, where compassion and professionalism belong together.','Ask about opportunities','tel:+447519560119')+layout(careers))

safeguarding='''<div class="notice urgent"><strong>Is someone in immediate danger?</strong><p>Call <a href="tel:999">999</a> now. This website and our general enquiries route are not emergency services.</p></div><h2>Everyone has the right to feel safe.</h2><p>Dayspring Centre is committed to safeguarding children, young people and adults from abuse, neglect, exploitation and avoidable harm. Concerns should be listened to and taken seriously.</p><h2>Our approach</h2>'''+ul(['Listen to people and respect their voice','Use appropriate safer recruitment procedures','Provide role-appropriate safeguarding training','Recognise and respond to concerns','Work with relevant statutory agencies','Keep clear and appropriate records','Learn from incidents and feedback','Share information appropriately when safeguarding requires it'])+f'''<h2>Raising a concern about Dayspring Centre</h2><p>Call <a href="tel:+447519560119">{PHONE}</a> to raise a concern relating to our service or a person receiving our support. If you cannot reach us, or the concern needs urgent statutory attention, contact the relevant local authority safeguarding service directly.</p><p>You may report concerns directly to statutory services without first contacting Dayspring Centre. Avoid putting confidential details into the website planner.</p><h2>Independent help and reporting</h2><p><a href="https://www.gov.uk/report-child-abuse">GOV.UK: report child abuse</a> explains how to contact a child’s local council social care team. For an adult safeguarding concern, contact adult social care at the relevant local council.</p><p><a href="https://www.gov.uk/find-local-council">Find your local council</a> to locate the appropriate service. Children and young people can also contact <a href="https://www.childline.org.uk/">Childline</a> on <a href="tel:08001111">0800 1111</a>.</p><h2>Privacy and safeguarding</h2><p>Information is treated with care. Confidentiality cannot be promised where sharing information with an appropriate authority may be necessary to protect someone from harm.</p>'''
page('safeguarding','Safeguarding','How to raise a safeguarding concern about children, young people or adults. Call 999 if someone is in immediate danger.',pagehero('Safeguarding','Your safety matters.<br>Your voice matters.','A concern does not have to wait until you have all the answers. If something feels wrong, speak up.','Raise a concern by phone','tel:+447519560119')+layout(safeguarding))

contact=f'''<h2>We’re ready to listen.</h2><p>Whether you are exploring support, enquiring about childcare, making a referral or looking for consultancy, start with a call. We’ll help you work out the next step.</p><div class="cards-small"><div class="small-card"><h3>Call Dayspring Centre</h3><p><a href="tel:+447519560119">{PHONE}</a></p><p>For support, childcare, referrals, careers and consultancy enquiries.</p></div><div class="small-card"><h3>Our registered office</h3><p>Dayspring Centre Limited<br>2 Athena Apartment<br>Jubilee Way, Sidcup<br>DA14 4BL, England</p><p>Please arrange any visit in advance.</p></div></div><p>We welcome enquiries from England. The availability and suitability of each service are confirmed with you before support is agreed.</p><div class="notice">For immediate danger, call <a href="tel:999">999</a>. For safeguarding information, see <a href="/safeguarding.html">our safeguarding page</a>.</div>'''+form()
page('contact','Contact us','Contact Dayspring Centre on +447519560119 to discuss childcare, support, referrals or consultancy in England.',pagehero('Contact Dayspring Centre','Every good beginning<br>starts with hello.','You might know exactly what you need, or simply want to explore the options. Either way, we’re here to help.','Call '+PHONE,'tel:+447519560119')+layout(contact))

areas='''<h2>Supporting people across England.</h2><p>Dayspring Centre is based in Sidcup, serving individuals, families and organisations across England.</p><p>The service you need, your location and the practical arrangements will shape what we can offer. We confirm availability, suitability, any travel arrangements and costs before you make a commitment.</p><div class="region-grid">'''+''.join(f'<div class="region">{r}</div>' for r in ['England'])+'''</div><h2>Based in Sidcup</h2><p>Our registered office is at 2 Athena Apartment, Jubilee Way, Sidcup, DA14 4BL. Please contact us before arranging a visit; a registered office address is not confirmation of a drop-in service.</p><h2>Tell us where you are</h2><p>Share your town or postcode area and a general description of the support you are looking for. We can then discuss the possibilities with you.</p>'''
page('areas','Areas we cover','Based in Sidcup and supporting England. Discuss service availability across England with Dayspring Centre.',pagehero('Areas we cover','Serving: England.<br>Care that starts with you.','Thoughtful support begins with understanding your community as well as your needs.')+layout(areas))

complaints='''<h2>Your feedback helps us improve.</h2><p>Please tell us if something has not met your expectations. You can raise a concern about our service, communication or support arrangements, or share a suggestion for improvement.</p><h2>How to get in touch</h2><p>Call <a href="tel:+447519560119">+447519560119</a>, or write to Dayspring Centre Limited, 2 Athena Apartment, Jubilee Way, Sidcup, DA14 4BL. Ask for your concern to be directed to the person responsible for complaints. You can also email <a href="mailto:dayspringcentre@dayspringcentre.co.uk">dayspringcentre@dayspringcentre.co.uk</a> with a general outline.</p><p>Explain what happened, roughly when it happened and what you would like us to consider. We will acknowledge your concern, explain who will review it and give you an expected response timeframe. We will look into what happened, share the outcome and any action to be taken, and explain how to ask for a further review if you remain unhappy.</p><p><a class="button" href="/complaints-procedure.html">View Our Complaints Procedure <span aria-hidden="true">↗</span></a></p><h2>Support to be heard</h2><p>Tell us if you need a different communication format or would like someone to help you raise your concern. If you are acting for another person, we may need to clarify their wishes or your authority to act.</p><div class="notice">If your concern involves safety or possible harm, use the <a href="/safeguarding.html">safeguarding routes</a>. Call 999 in an emergency.</div>'''+form('complaints')
page('complaints','Feedback & complaints','Tell Dayspring Centre about a concern, complaint or suggestion. Find contact details and safeguarding routes.',pagehero('Feedback & complaints','We’re listening.<br>Help us put things right.','Your experience matters. Feedback gives us the opportunity to understand, respond and learn.','Discuss your feedback','tel:+447519560119')+layout(complaints))


procedure = """<h2>1. Tell us what happened</h2><p>Contact us on <a href="tel:+447519560119">+447519560119</a>, email <a href="mailto:dayspringcentre@dayspringcentre.co.uk">dayspringcentre@dayspringcentre.co.uk</a>, or write to Dayspring Centre Limited, 2 Athena Apartment, Jubilee Way, Sidcup, DA14 4BL.</p><p>Give a general outline of the issue, when it happened, the service involved and what you would like us to consider. Please contact us before sharing confidential records so that we can agree an appropriate route.</p><h2>2. We acknowledge and explain the next step</h2><p>Your concern will be directed to the person responsible for complaints. We will clarify the issues, explain who will review them and tell you the expected response timeframe. If you need communication support or someone to help you, please let us know.</p><h2>3. We look into your concern</h2><p>We review the relevant information and speak with those involved where appropriate. We may contact you to understand your experience more clearly. Information is handled with care and shared only as appropriate to the review or safeguarding obligations.</p><h2>4. We explain the outcome</h2><p>We will explain our findings, the reasons for the outcome and any steps to put things right or improve the service. If more time is needed, we will explain the reason and give a revised expected timeframe.</p><h2>5. Ask for a further review</h2><p>If you remain unhappy, contact us and explain which parts of the response you would like reviewed. Ask for the concern to be considered by an appropriate senior person. We will explain the review arrangements and any relevant external route.</p><h2>Independent routes and urgent concerns</h2><p>If your support was arranged by a local authority or another commissioning organisation, you can also contact that organisation about its complaints process. For concerns about registered childcare, see <a href="https://www.gov.uk/complain-about-childcare">GOV.UK guidance on complaining about childcare</a>. Data-protection concerns may be raised with the <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner’s Office</a>.</p><div class="notice urgent"><strong>Safeguarding must not wait for a complaints review.</strong><p>Use the <a href="/safeguarding.html">safeguarding reporting routes</a> if someone may be at risk. If anyone is in immediate danger, call <a href="tel:999">999</a>.</p></div><h2>Request the full organisational policy</h2><p>Contact us to request a copy of the full complaints policy and any service-specific arrangements. This page sets out the public complaints journey; any applicable statutory complaints rights remain unchanged.</p>"""
page('complaints-procedure','Complaints procedure','How to raise a complaint, what happens next and how to ask for a review at Dayspring Centre.',pagehero('Complaints procedure','A clear way to be heard.','Tell us your concern. We will explain the next steps, keep you informed and use what we learn to improve.','Raise a concern','/complaints.html')+layout(procedure))

policies={
'privacy':('Privacy information','How this website handles information.', '''<h2>Who we are</h2><p>This website is operated for Dayspring Centre Limited, company number 11290144. Dayspring Centre Limited is registered with the Information Commissioner’s Office under ICO Data Protection Registration No. <strong>00014845068</strong>. Contact us on +447519560119 or write to 2 Athena Apartment, Jubilee Way, Sidcup, DA14 4BL about privacy questions.</p><h2>The conversation planner</h2><p>The optional forms on this site create a summary in your browser. They do not submit an enquiry to Dayspring Centre or store form contents in browser storage. Any summary you choose to download is saved on your device. Keep it secure, especially on shared devices.</p><p>Do not enter health information, detailed safeguarding concerns or another person’s personal records. Call us first to agree how to share information appropriately. If you choose to use an email or telephone application, that service will handle the information you share according to its own terms.</p><h2>Technical information</h2><p>Vercel hosts this website and processes technical request information, such as IP addresses and browser information, to deliver and protect the site. Google Fonts supplies the typefaces; loading these fonts makes requests to Google. These providers may process data outside the UK under their applicable arrangements. See <a href="https://vercel.com/legal/privacy-policy">Vercel’s privacy policy</a> and <a href="https://developers.google.com/fonts/faq/privacy">Google Fonts privacy information</a>.</p><h2>Preferences on your device</h2><p>We use local storage for accessibility preferences and whether you have dismissed the cookie notice. We do not use advertising trackers or analytics cookies. You can clear these choices through your browser settings.</p><h2>When you contact us directly</h2><p>Dayspring Centre will need relevant contact information to respond. Before detailed referral, care or recruitment information is collected, ask for the privacy information appropriate to that service, including purposes, lawful basis, recipients and retention arrangements. This website notice does not replace those service-specific notices.</p><h2>Your rights and questions</h2><p>Depending on the circumstances, data protection law gives you rights to access, correct, erase or restrict use of your personal information, and to object to certain uses. Where processing is based on consent, you may withdraw it. Contact Dayspring Centre to ask about your information. You can also raise a concern with the <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner’s Office</a>.</p>'''),
'cookies':('Cookies & device storage','A simple website with no advertising trackers.', '''<h2>What this site uses</h2><p>This site does not set analytics or advertising cookies. It saves the following choices using local storage in your browser:</p><ul><li><strong>dayspring-notice:</strong> whether you dismissed the privacy notice.</li><li><strong>dayspring-display:</strong> your larger-text and contrast preferences.</li></ul><p>These choices stay on your device until you clear site data. Form entries are not saved to local storage. Necessary hosting or security technologies may be used by our hosting provider to deliver and protect the site.</p><h2>Changing your choices</h2><p>Use the Accessibility button to change display preferences. The Cookie settings link at the foot of every page reopens the notice. To remove saved choices, clear this website’s data in your browser settings.</p><h2>External services</h2><p>Fonts load from Google Fonts. External links only take you to another service when you choose to follow them. See our <a href="/privacy.html">privacy information</a> for more about these services.</p>'''),
'accessibility':('Accessibility','A more comfortable website, for more people.', '''<h2>Designed to be easier to use</h2><p>This website includes keyboard navigation, visible focus outlines, labelled form fields, a skip-to-content link, descriptive headings, responsive layouts and text alternatives for meaningful images.</p><p>The Accessibility button lets you increase text size and use a higher-contrast palette. You can also zoom with your browser. Motion is reduced when your device requests reduced motion.</p><h2>Our aim</h2><p>We aim to follow WCAG 2.2 AA accessibility principles. This is a design aim, not a claim of independent certification. We welcome reports of any barrier you encounter.</p><h2>Need information another way?</h2><p>Call <a href="tel:+447519560119">+447519560119</a> or write to our registered office. Tell us which information you need and the format or communication support that would help.</p><h2>Report a website problem</h2><p>Let us know the page you were using, what you were trying to do and, if you wish, the device or assistive technology involved. This helps us understand and address the issue.</p>'''),
'terms':('Website terms','Using the Dayspring Centre website.', '''<h2>About the information here</h2><p>This website provides general information about Dayspring Centre Limited and its services. It is not clinical, legal or individual care advice. Services, availability, eligibility, fees and arrangements must be discussed and agreed with Dayspring Centre.</p><h2>Service agreements</h2><p>An enquiry or conversation summary does not create a care arrangement, childcare booking, employment agreement or consultancy contract. Any service is subject to suitability, capacity, applicable registration and a separate agreement.</p><h2>Registration and imagery</h2><p>Ofsted registration EY552018 relates to childcare provision. No CQC registration, rating, formal partnership or inspection outcome is implied for other services. Images are illustrative and are not evidence of actual staff, premises or people receiving support.</p><h2>Links and availability</h2><p>We link to external resources for convenience. Their operators are responsible for their content and privacy practices. Website availability and external links may change.</p><h2>Contact</h2><p>Dayspring Centre Limited, company no. 11290144. Registered office: 2 Athena Apartment, Jubilee Way, Sidcup, DA14 4BL. Telephone: <a href="tel:+447519560119">+447519560119</a>.</p>'''),
'equality':('Equality & inclusion','Respecting the whole person.', '''<h2>A place to belong</h2><p>Dayspring Centre’s approach recognises each person’s culture, identity, beliefs, abilities and circumstances. We want people to be treated with dignity and to have a meaningful voice in decisions about their support.</p><h2>Practical inclusion</h2><p>Tell us about communication needs, accessibility requirements or cultural and personal preferences when you enquire. We will discuss what adjustments and arrangements may be appropriate before agreeing a service.</p><h2>Raise a concern</h2><p>If you feel you have been treated unfairly in connection with Dayspring Centre, please contact us. You can use our <a href="/complaints.html">feedback and complaints route</a>, or the <a href="/safeguarding.html">safeguarding route</a> where there is a risk of harm.</p>'''),
'modern-slavery':('Modern slavery & exploitation','Dignity, freedom and safe working.', '''<h2>Our position</h2><p>Dayspring Centre opposes slavery, forced labour, human trafficking and exploitation. Respect for people’s rights and dignity is central to the support we seek to provide.</p><h2>Raising a concern</h2><p>If you suspect exploitation involving our services or working arrangements, contact Dayspring Centre on <a href="tel:+447519560119">+447519560119</a>. Where there is a risk of harm, use the appropriate statutory safeguarding route. Call 999 if someone is in immediate danger.</p><h2>Further information</h2><p>This page explains our public position and reporting route. It is not presented as an audited supply-chain report or a statutory annual modern slavery statement. Contact us to request relevant organisational policies.</p>''')}
for slug,(title,lead,body) in policies.items():
    page(slug,title,lead+' Dayspring Centre Limited.',pagehero(title,title,lead,None)+layout(body))
page('404','Page not found','Find your way back to Dayspring Centre.',pagehero('Page not found','Let’s get you<br>back on track.','We couldn’t find that page. Explore our services or get in touch and we’ll help you find what you need.','Back to home','/')+layout('<h2>Where would you like to go?</h2>'+ul(['<a href="/services.html">Explore our services</a>','<a href="/contact.html">Contact Dayspring Centre</a>','<a href="/referrals.html">Make a referral</a>','<a href="/safeguarding.html">Safeguarding information</a>'])))
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+SITE+('/' if slug=='index' else '/'+slug+'.html')+'</loc></url>' for slug in pages if slug!='404')+'</urlset>',encoding='utf-8')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+SITE+'/sitemap.xml\n',encoding='utf-8')
print(f'Built {len(pages)} static HTML pages.')
